### ISSUE TITLE
plain text attachment is displayed as entire text instead of just an attachement

### ISSUE THREAD

**Issue by JimEllisRI** [ayamadori/EmlReader#3]
I have a text file as an attachment in an eml.  MS Outlook diskplays it properly.  This program displays the text document as if it was pasted into the email.  The other content (not attachments) is not shown, unsure if it hiding the content.

**Comment by ayamadori** [comment]
Thanks for the bug report! I'll check this issue.

Left: Windows Mail app, Right: EML Reader
![image](https://user-images.githubusercontent.com/7036267/192573822-b605ede5-2f60-4343-9123-b04294922801.png)

**Comment by ayamadori** [comment]
Maybe fixed.
Please wait and try next version.
![image](https://user-images.githubusercontent.com/7036267/193395994-dc440aaf-2c47-4b69-b9fc-6362c98b30c1.png)
